excluded:
  - Pods/**/*

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_spacing
  - explicit_init
  - joined_default_parameter
  - nimble_operator
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - sorted_imports
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
 

disabled_rules:
  - unused_optional_binding
  - identifier_name
  - multiple_closures_with_trailing_closure

line_length:
  ignores_function_declarations: true
  ignores_comments: true
